---
# tasks file for .
- name: install pxc package
  command: echo 'stub'
  tags:
  - bootstrap
  - setup
- name: (debian) install pxc package -> add key
  apt_key: state=present keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A
  sudo: yes
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
- name: (debian) install pxc package -> add repositories
  copy: src=./percona.list dest=/etc/apt/sources.list.d/percona.list
  sudo: yes
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
- name: (debian) install pxc package -> add repositories
  apt: state=present name=percona-xtradb-cluster-full-55
  sudo: yes
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"
- name: (redhat) install depend packages
  yum: state=present name='{{ item }}'
  with_items:
  - 'epel-release'
  - 'nc'
  - 'http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm'
  sudo: yes
  when: ansible_os_family == "Redhat"
- name: (redhat) install percona db
  yum: state=present name='Percona-XtraDB-Cluster-55'
  sudo: yes
  when: ansible_os_family == "Redhat"
