# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-6.6"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define vm_name = "test-centos66" do |config|
    config.vm.hostname = vm_name

    ip = "192.168.99.100"
    config.vm.network :private_network, ip: ip
  end

  config.ssh.insert_key = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbook.yml"
  end
end